name = "TidierPlots"
uuid = "337ecbd1-5042-4e2a-ae6f-ca776f97570a"
authors = ["Randall Boyes <33524191+rdboyes@users.noreply.github.com> and contributors"]
version = "0.6.5"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TidierData = "fe2206b3-d496-4ee9-a338-6a095c4ece80"

[compat]
CairoMakie = "0.11"
CategoricalArrays = "0.10"
Colors = "0.12"
DataFrames = "1.5"
GLM = "1.9"
KernelDensity = "0.6"
Loess = "0.6"
Makie = "0.20.8"
Reexport = "1.2"
TidierData = "0.15"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
