name = "TidierPlots"
uuid = "337ecbd1-5042-4e2a-ae6f-ca776f97570a"
version = "1.0.0"
authors = ["Randall Boyes <33524191+rdboyes@users.noreply.github.com> and contributors"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
TidierData = "fe2206b3-d496-4ee9-a338-6a095c4ece80"

[compat]
CairoMakie = "0.15"
CategoricalArrays = "0.10, 1"
ColorSchemes = "3.24"
Colors = "0.13"
DataFrames = "1.7"
Dates = "1.10"
Documenter = "0.27"
FixedPointNumbers = "0.8"
Format = "1.3"
GLM = "1.9"
Images = "0.26.2"
KernelDensity = "0.6"
Loess = "0.6"
Makie = "0.24"
Markdown = "1.10"
Parquet2 = "0.2"
PooledArrays = "1.4"
RDatasets = "0.7.7"
Random = "1.10"
Reexport = "1.2"
Statistics = "1.10"
Test = "1.10"
TestItemRunner = "1.1.4"
TestItems = "1.0.0"
TidierData = "0.17"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
